### ISSUE TITLE
Statistics Bug

### ISSUE THREAD

**Issue by orvzjhp** [fskreuz/Tree-Trail#113] opened 2015-03-15 17:25 UTC
In the "Select tree" dropdown, it shows the municipalities or the place and in the municipalities radio button section, it shows the type of trees.

**Comment by chichiJPN** [comment] 2015-03-16 07:33
f*ck you orvz

**Comment by MarianneBorces** [comment] 2015-03-16 18:00
This is correct @orvzjhp . not a bug. the data lang. closing this.

**Closed by MarianneBorces** 2015-03-16 18:00 UTC
Labels: Bug
