### ISSUE TITLE
Log In Redirection Bug

### ISSUE THREAD

**Issue by mitziel** [fskreuz/Tree-Trail#87] opened 2015-03-15 02:51 UTC
-Super Admin shouldn't have an access to Tree-trail Map Home page along with its function in the Nav Bar(like the Statistics, About and Filter badges because only Admin Users are entitled to have that functions)
-Super Admin should be directed toward the Dashboard Page directly and only (where it can do user management, its only sole function)

**Comment by fskreuz** [comment] 2015-03-15 04:24
Ha? Ana si Jeana nga ang super admin mura rag guest if mu visit siya sa page. Pagstorya sah mo about ani. Dismissing as won't fix.

**Comment by fskreuz** [comment] 2015-03-15 06:44
https://github.com/fskreuz/Tree-Trail/commit/b6e3c983efa9d80c0ea62b4e56dcddcebd30c358

**Comment by MarianneBorces** [comment] 2015-03-15 12:00
This is still a bug

**Comment by chuakarlo** [comment] 2015-03-16 00:06
This is not a bug. Misunderstanding ra ni. Ako ni i.fix laters.. :)

**Comment by chuakarlo** [comment] 2015-03-16 01:25
modified and fixed.. :) merging nlng kulang

**Closed** 2015-03-16 17:52 UTC
Labels: Bug
